title: Sean's Data Garage
logo: /assets/img/profile.jpeg
description: Hello! This is an overview of some work I've done in the world of data science and anylsis.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
